version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-bi:
    image: devtrends/mongodb-bi-connector
    container_name: mongo-bi
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/entreprise
      - BI_PORT=3307
    ports:
      - "3307:3307"

volumes:
  mongo_data:
